dist: bionic
os: linux
language: python
python:
- "3.6"

env:
  global:
    - RELEASE_BRANCH=release-0.0.4

if: |
  branch in (travis-ci, env(RELEASE_BRANCH)) AND \
  fork = false AND \
  type = push 

jobs:
  include:
    - stage: build
      name: operator-and-bundles
      env: 
        - OPERATOR_SDK_VERSION=v0.17.0
        - ENVIRONMENT=ci
      before_install:
      - build/scripts/build/install-deps
      script:
      - build/scripts/build/build
      - build/scripts/build/login
      - build/scripts/build/push
#    - stage: test-k8s
#      name: k8s_v1.14.0-olm_0.13.0-minikube_v1.9.2
#      env: 
#        - MINIKUBE_VERSION=v1.9.2
#        - KUBERNETES_VERSION=v1.14.0
#        - OLM_VERSION=0.13.0
#        - ENVIRONMENT=ci
#        - DISTRIBUTION=k8s
#        - MEMORY=6144
#      before_install:
#      - build/scripts/test/k8s/install-deps
#      install:
#      - build/scripts/test/k8s/start
#      before_script:
#      - build/scripts/test/common/install-olm
#      script:
#      - build/scripts/build/generate
#      - build/scripts/test/k8s/test-operator
#      - build/scripts/test/k8s/test-argocd
#      - build/scripts/test/k8s/test-cleanup
#      after_script:
#      - build/scripts/test/k8s/stop
#    - name: k8s_v1.17.0-olm_0.14.1-minikube_v1.9.2
#      env: 
#        - MINIKUBE_VERSION=v1.9.2
#        - KUBERNETES_VERSION=v1.17.0
#        - OLM_VERSION=0.14.1
#        - ENVIRONMENT=ci
#        - DISTRIBUTION=k8s
#        - MEMORY=6144
#      before_install:
#      - build/scripts/test/k8s/install-deps
#      install:
#      - build/scripts/test/k8s/start
#      before_script:
#      - build/scripts/test/common/install-olm
#      script:
#      - build/scripts/build/generate
#      - build/scripts/test/k8s/test-operator
#      - build/scripts/test/k8s/test-argocd
#      - build/scripts/test/k8s/test-cleanup
#      after_script:
#      - build/scripts/test/k8s/stop
#    - name: k8s_v1.18.0-olm_0.14.1-minikube_v1.9.2
#      env: 
#        - MINIKUBE_VERSION=v1.9.2
#        - KUBERNETES_VERSION=v1.18.0
#        - OLM_VERSION=0.14.1
#        - ENVIRONMENT=ci
#        - DISTRIBUTION=k8s
#        - MEMORY=6144
#      before_install:
#      - build/scripts/test/k8s/install-deps
#      install:
#      - build/scripts/test/k8s/start
#      before_script:
#      - build/scripts/test/common/install-olm
#      script:
#      - build/scripts/build/generate
#     - build/scripts/test/k8s/test-operator
#      - build/scripts/test/k8s/test-argocd
#      - build/scripts/test/k8s/test-cleanup
#      after_script:
#      - build/scripts/test/k8s/stop
    - stage: test-ocp3
      name: ocp3_3.11.0-olm_0.13.0-minishift_1.34.2   
      env: 
        - MINISHIFT_VERSION=1.34.2
        - OLM_VERSION=0.13.0
        - ENVIRONMENT=ci
        - DISTRIBUTION=ocp3
        - MEMORY=7200
      before_install:
      - build/scripts/test/ocp3/install-deps
      install:
      - build/scripts/test/ocp3/start
      before_script:
      - build/scripts/test/common/install-olm
      script:
      - build/scripts/build/generate
      - build/scripts/test/ocp/test-operator
      - build/scripts/test/ocp/test-argocd
      - build/scripts/test/ocp/test-cleanup
      after_script:
      - build/scripts/test/ocp3/stop
