version: 2.1
jobs:
  operator-and-bundles:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build & Publish operator and bundles
          environment:
            OPERATOR_SDK_VERSION: v0.17.0
          command: |
            pyenv global 3.6.5
            build/scripts/build/install-deps
            build/scripts/build/build
            build/scripts/build/login
            build/scripts/build/push
  k8s-v1140-olm-0130-minikube-v192:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Kubernetes v1.14.0 & OLM 0.13.0 (Minikube v1.9.2)
          environment:
            MINIKUBE_VERSION: v1.9.2
            KUBERNETES_VERSION: v1.14.0
            OLM_VERSION: 0.13.0
            ENVIRONMENT: ci
            DISTRIBUTION: k8s
            MEMORY: "6144"
          command: |
            build/scripts/test/k8s/install-deps
            build/scripts/build/generate
            build/scripts/test/k8s/start
            build/scripts/test/common/install-olm
            build/scripts/test/k8s/test-operator
            build/scripts/test/k8s/test-argocd
            build/scripts/test/k8s/test-cleanup
            build/scripts/test/k8s/stop
  k8s-v1170-olm-0141-minikube-v192:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Kubernetes v1.17.0 & OLM 0.14.1 (Minikube v1.9.2)
          environment:
            MINIKUBE_VERSION: v1.9.2
            KUBERNETES_VERSION: v1.17.0
            OLM_VERSION: 0.14.1
            ENVIRONMENT: ci
            DISTRIBUTION: k8s
            MEMORY: "6144"
          command: |
            build/scripts/test/k8s/install-deps
            build/scripts/build/generate
            build/scripts/test/k8s/start
            build/scripts/test/common/install-olm
            build/scripts/test/k8s/test-operator
            build/scripts/test/k8s/test-argocd
            build/scripts/test/k8s/test-cleanup
            build/scripts/test/k8s/stop
  k8s-v1180-olm-0141-minikube-v192:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Kubernetes v1.18.0 & OLM 0.14.1 (Minikube v1.9.2)
          environment:
            MINIKUBE_VERSION: v1.9.2
            KUBERNETES_VERSION: v1.18.0
            OLM_VERSION: 0.14.1
            ENVIRONMENT: ci
            DISTRIBUTION: k8s
            MEMORY: "6144"
          command: |
            build/scripts/test/k8s/install-deps
            build/scripts/build/generate
            build/scripts/test/k8s/start
            build/scripts/test/common/install-olm
            build/scripts/test/k8s/test-operator
            build/scripts/test/k8s/test-argocd
            build/scripts/test/k8s/test-cleanup
            build/scripts/test/k8s/stop

workflows:
  version: 2
  continuous-integration:
    jobs:
      - operator-and-bundles:
          filters:
            branches:
              only: 
                - circle-ci
                - release-0.0.4
      - k8s-v1140-olm-0130-minikube-v192:
          requires:
            - operator-and-bundles
          filters:
            branches:
              only: 
                - circle-ci
                - release-0.0.4
      - k8s-v1170-olm-0141-minikube-v192:
          requires:
            - operator-and-bundles
          filters:
            branches:
              only: 
                - circle-ci
                - release-0.0.4
      - k8s-v1180-olm-0141-minikube-v192:
          requires:
            - operator-and-bundles
          filters:
            branches:
              only: 
                - circle-ci
                - release-0.0.4
