{{- if .Values.openshift.enabled -}}
{{- if .Values.openshift.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "argo-cd.server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.server.name }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
{{- with .Values.openshift.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  host: {{ .Values.openshift.route.host | quote }}
  to:
    kind: Service
    name: {{ template "argo-cd.server.fullname" . }}
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect 
  wildcardPolicy: None
{{ include "argo-cd.helmRouteFix" $ }}  
{{- end }}
{{- end }}

