apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/disposab1e/argocd-operator-helm-registry-ocp:0.0.6
  displayName: Argo CD Operators
  publisher: Argo CD
